name: CI Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Go dependencies
      run: |
        go get -v -t -d ./...

    - name: Install build dependencies
      run: sudo apt-get install libsystemd-dev

    - name: Build
      run: make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: prometheus-postscreen-exporter
        path: prometheus-postscreen-exporter
